# Generated by Django 5.2.4 on 2026-07-18 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/')),
                ('category', models.CharField(choices=[('PRODUCT_ADDED', 'Product Added'), ('NEW_ORDER', 'New Order'), ('PRODUCT_UPDATED', 'Product Updated'), ('PRODUCT_DELETED', 'Product Deleted'), ('AI_GENERATION_COMPLETED', 'AI Generation Completed'), ('AI_GENERATION_FAILED', 'AI Generation Failed'), ('PROFILE_UPDATED', 'Profile Updated')], default='PRODUCT_ADDED', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
