# Generated by Django 5.2.4 on 2025-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a seller and can upload products.'),
        ),
    ]
