# Generated by Django 5.2.4 on 2026-07-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentdetailsmodel',
            name='aadhaar_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='governmentdetailsmodel',
            name='gst_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='governmentdetailsmodel',
            name='income_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='governmentdetailsmodel',
            name='occupation_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='governmentdetailsmodel',
            name='overall_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='governmentdetailsmodel',
            name='pan_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20),
        ),
    ]
