# Generated by Django 5.2.4 on 2026-07-20 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_governmentdetailsmodel_aadhaar_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstmodel',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}$', 'Invalid GST number.')]),
        ),
    ]
