# Generated by Django 5.2.4 on 2025-07-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(blank=True, max_length=100, null=True)),
                ('update_by', models.CharField(blank=True, max_length=100, null=True)),
                ('api_url', models.CharField(max_length=255)),
                ('request_data', models.TextField()),
                ('response_data', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('ip_address', models.CharField(max_length=45)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('request_method', models.CharField(default='GET', max_length=10)),
                ('request_user', models.CharField(default='AnonymousUser', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(blank=True, max_length=100, null=True)),
                ('update_by', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.CharField(max_length=6)),
                ('device', models.CharField(max_length=254)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('pan', 'PAN')], default='mobile', max_length=20)),
                ('purpose', models.CharField(default='login', max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('expired', 'Expired'), ('verified', 'Verified')], default='generated', max_length=10)),
            ],
            options={
                'verbose_name': 'OTP Log',
                'verbose_name_plural': 'OTP Logs',
            },
        ),
    ]
