# Generated by Django 5.2.4 on 2026-07-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVisualEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(help_text='768-dimensional float array from text-embedding-004')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visual_embedding', to='catalogue.productmodel')),
            ],
        ),
    ]
